### ISSUE TITLE
struct.error for parse_null_delimited_record function

### ISSUE THREAD

**Issue by l0gm0nk3y** [davidpany/WMI_Forensics#1]
First, I wanted to thank you for sharing your code!  

When you have a moment, I was hoping you could look into why the parser is throwing the following exception during the unpack: 
File "CCM_RUA_Finder.py", line 361, in parse_null_delimited_record
    file_size = struct.unpack("L", header_data_match.groups()[4])[0]
struct.error: unpack requires a string argument of length 8

I have tried two different OBJECTS.DATA files and both give the same results.

When I put in a exception (catch -> ignore) for the  parse_null_delimited_record function,  I only get minimal records parsed (40+) with several hundred ignored.

**Comment by davidpany** [comment]
Thanks for letting me know about this! By any chance, are you running on a Mac? 

If so, I think the update in the mac_test branch may fix the issue. https://github.com/davidpany/WMI_Forensics/blob/mac_test/CCM_RUA_Finder.py

Please let me know if that works for you. Thanks!

**Comment by l0gm0nk3y** [comment]
Yes, I was running it on a Mac.  The code from this branch does fix the issue.  Thanks again!
